# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Network(object):
    def setupUi(self, Network):
        Network.setObjectName("Network")
        Network.resize(890, 618)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Network)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 891, 621))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.localIp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.localIp.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.localIp.setFont(font)
        self.localIp.setText("")
        self.localIp.setObjectName("localIp")
        self.gridLayout.addWidget(self.localIp, 1, 1, 1, 1)
        self.publicIp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.publicIp.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.publicIp.setFont(font)
        self.publicIp.setText("")
        self.publicIp.setObjectName("publicIp")
        self.gridLayout.addWidget(self.publicIp, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.getIpButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.getIpButton.setObjectName("getIpButton")
        self.gridLayout_2.addWidget(self.getIpButton, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.uploadLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uploadLabel.setFont(font)
        self.uploadLabel.setText("")
        self.uploadLabel.setObjectName("uploadLabel")
        self.gridLayout_4.addWidget(self.uploadLabel, 0, 1, 1, 1)
        self.downloadLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.downloadLabel.setFont(font)
        self.downloadLabel.setText("")
        self.downloadLabel.setObjectName("downloadLabel")
        self.gridLayout_4.addWidget(self.downloadLabel, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.speedTestButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.speedTestButton.setObjectName("speedTestButton")
        self.gridLayout_2.addWidget(self.speedTestButton, 1, 0, 1, 1)

        self.retranslateUi(Network)
        QtCore.QMetaObject.connectSlotsByName(Network)

    def retranslateUi(self, Network):
        _translate = QtCore.QCoreApplication.translate
        Network.setWindowTitle(_translate("Network", "Form"))
        self.label_2.setText(_translate("Network", "IP Publique:"))
        self.label.setText(_translate("Network", "IP Locale:"))
        self.getIpButton.setText(_translate("Network", "Récupérer les IP"))
        self.label_4.setText(_translate("Network", "Download:"))
        self.label_3.setText(_translate("Network", "Upload:"))
        self.speedTestButton.setText(_translate("Network", "Lancer le Speedtest"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Network = QtWidgets.QWidget()
    ui = Ui_Network()
    ui.setupUi(Network)
    Network.show()
    sys.exit(app.exec_())
